### ISSUE TITLE
Refusing to install intruder as a dependency of itself

### ISSUE THREAD

**Issue by matthiaskern** [stevenmiller888/intruder#1]
Can't install intruder on Arch Linux and am not able to make any sense of this. 

```
mutt@tpad: ~/Workspace/Projects/intruder$ npm install intruder
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "intruder"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ENOSELF

npm ERR! Refusing to install intruder as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matt/Workspace/Projects/intruder/npm-debug.log
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'intruder' ]
2 info using npm@3.3.4
3 info using node@v4.1.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData intruder
8 silly fetchNamedPackageData intruder
9 silly mapToRegistry name intruder
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/intruder
13 verbose request uri https://registry.npmjs.org/intruder
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:08:41 PM
16 verbose request id ae28ec58cfef44f0
17 verbose etag "D1BC6PT45VZPW70T9Y9LAOS0B"
18 http request GET https://registry.npmjs.org/intruder
19 http 304 https://registry.npmjs.org/intruder
20 verbose headers { date: 'Sun, 27 Sep 2015 12:08:42 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"D1BC6PT45VZPW70T9Y9LAOS0B"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1246-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1443355722.227805,VS0,VE179',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Sun, 27 Sep 2015 12:08:42 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"D1BC6PT45VZPW70T9Y9LAOS0B"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1246-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1443355722.227805,VS0,VE179',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/intruder from cache
23 verbose get saving intruder to /home/matt/.npm/registry.npmjs.org/intruder/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install intruder as a dependency of itself
41 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /home/mutt/Workspace/Projects/intruder
43 error Linux 4.1.6-1-ARCH
44 error argv "/usr/bin/node" "/usr/bin/npm" "install" "intruder"
45 error node v4.1.1
46 error npm  v3.3.4
47 error code ENOSELF
48 error Refusing to install intruder as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by matthiaskern** [comment]
nevermind, works with node v0.12.0

**Comment by stevenmiller888** [comment]
Sweet, glad you got it installed. Just wanted to add that this won't work on Linux yet because it uses airport (an OS X utility) to sniff packets.
