### ISSUE TITLE
wlan0     Interface doesn't support scanning.

### ISSUE THREAD

**Issue by shubhambatra** [stevenmiller888/intruder#15]
home/shubham/Documents/Test/index.js:8
    if (err) throw new Error(err);
             ^

Error: Error: wlan0     Interface doesn't support scanning.

```
at /home/shubham/Documents/Test/index.js:8:20
at /home/shubham/Documents/Test/node_modules/intruder/lib/index.js:59:21
at ChildProcess.handleClose (/home/shubham/Documents/Test/node_modules/network-scanner/lib/index.js:72:14)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:484:12)
```

**Comment by felegy-norbert** [comment]
Did you manage to solve this? I have the same error.

**Comment by zoutepopcorn** [comment]
Me to on HP and Ubuntu 16.04 now.
