### ISSUE TITLE
Error: network not found

### ISSUE THREAD

**Issue by srijishks** [stevenmiller888/intruder#28]
Hi Steve,

I got this error,

```
Error: Error: network not found
    at D:\fakepath\intruder\index.js:10:20
    at D:\fakepath\intruder\node_modules\intruder\lib\index.js:63:26
    at ChildProcess.handleClose (D:\fakepath\intruder\node_modules\netwo
rk-scanner\lib\index.js:79:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

```

Could you please tell me how to solve it?

**Comment by kshivang** [comment]
Wifi network you are trying to crack must be not in range.
First decide which wifi network you want to crack. Then replace 'Home' with 'wifi_you_want_to_crack' 
in 
```js
var Intruder = require('intruder');
var intruder = Intruder();

intruder
  .on('attempt', function(ivs) {
    console.log(ivs);
  })
  .crack('Home', function(err, key) {
    if (err) throw new Error(err);
    console.log(key);
  });
```

**Comment by lopugit** [comment]
my network is in range but still no network found :O

https://imgur.com/a/pq2Dote

**Comment by stratienko** [comment]
Do you still support the package?

I get the same error when I try to access my own Wifi network at home. My laptop is connected to this network, so it's definitely in range.

**Comment by srijishks** [comment]
I think the issue not yet fixed but you can use Kali linux to hack wifi. This OS have some build-in tools for penetration

**Comment by imronpuji** [comment]
ahh same
